name: amit test variables workflow
env:
  SOMEVAR: hello
on:
  workflow_dispatch
jobs:
  initialize_variable:
    runs-on: ubuntu-latest
  use_variable:
    runs-on: ubuntu-latest
    needs: initialize_variable
    steps:
      - name: usevar
        run: echo "var is ${{ env.SOMEVAR }}"