name: amit test variables workflow
on:
  workflow_dispatch
jobs:
  initialize_variable:
    runs-on: ubuntu-latest
    steps:
      - name: setvar
        run: echo "SOMEVAR=hello" > $GITHUB_ENV
        run: echo "var is ${{ env.SOMEVAR }}"

  use_variable:
    runs-on: ubuntu-latest
    needs: initialize_variable
    steps:
      - name: usevar
        run: echo "var is ${{ env.SOMEVAR }}"