name: dispatch workflow
on:
  workflow_dispatch
jobs:
  say_hi:
    runs-on: ubuntu-latest
    steps:
      - name: msg
        run: echo "Invoked by call_workflow"

  # Dependency to a forking workflow
  workflow_run:
    workflows: ["dispatch workflow"]
    type:
      - complete
jobs:
  say_hi2:
    runs-on: ubuntu-latest
    steps:
      - name: msg
        run: echo "manual triger"